# Generated by Django 5.1.7 on 2025-04-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_inventoryitem_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.IntegerField(unique=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.IntegerField()),
                ('inventory_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('per_unit_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
