# Generated by Django 5.1.7 on 2025-04-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_inventory_inventorylog_delete_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='inventory_id',
            field=models.CharField(max_length=255),
        ),
    ]
