# Generated by Django 5.1.7 on 2025-04-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_inventorylog_inventory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('organization', models.CharField(default='', max_length=100)),
                ('item', models.CharField(default='', max_length=100)),
                ('text', models.TextField()),
                ('sale_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('car_model', models.CharField(default='', max_length=100)),
                ('claim_id', models.CharField(default='', max_length=100)),
                ('warranty_id', models.CharField(default='', max_length=100)),
                ('dealership', models.CharField(default='', max_length=100)),
                ('VIN', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
