# Generated by Django 5.1.7 on 2025-04-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_complaint_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='estimated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
