# Generated by Django 5.1.7 on 2025-04-09 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_inspection_estimated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealershipInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Rust Protection', 'Rust Protection'), ('Fabric Protection', 'Fabric Protection'), ('Paint Protection', 'Paint Protection'), ('VIN Etching', 'VIN Etching'), ('Extended Warranties', 'Extended Warranties'), ('Window Tinting', 'Window Tinting'), ('Car Alarms', 'Car Alarms'), ('Rear-Seat Entertainment System', 'Rear-Seat Entertainment System'), ('Roof Rack', 'Roof Rack'), ('Lojack', 'Lojack'), ('Gap Insurance', 'Gap Insurance'), ('Dent Protection', 'Dent Protection'), ('Key Protection', 'Key Protection'), ('Nitrogen Filled Tires', 'Nitrogen Filled Tires'), ('Financing', 'Financing'), ('Tire and Wheel Protection', 'Tire and Wheel Protection'), ('Undercoating', 'Undercoating')], max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dealership')),
            ],
        ),
    ]
