# Generated by Django 5.1.7 on 2025-04-09 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dealership_dealershipinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=100)),
                ('dealership', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('expected_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], max_length=20)),
                ('date_of_order', models.DateField()),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dealership')),
            ],
        ),
    ]
