# Generated by Django 5.1.7 on 2025-04-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_sale_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dealership',
        ),
        migrations.DeleteModel(
            name='DealershipInventory',
        ),
        migrations.DeleteModel(
            name='Dealership',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
